#!/usr/bin/env bash
#
#    00-header - create the header of the MOTD
#    Copyright (c) 2013 Nick Charlton
#    Copyright (c) 2009-2010 Canonical Ltd.
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

GREEN='\033[0;32m'
NC='\033[0m' # No Color

printf "\n"
if command -v figlet >/dev/null 2>&1 && [ -r /etc/update-motd.d/nancyj.flf ]; then
    printf "%b%s%b\n" "$GREEN" "$(figlet -c -f /etc/update-motd.d/nancyj.flf -w 120 "$(hostname -s | awk '{print toupper($0)}')")" "$NC"
else
    printf "%b%s%b\n" "$GREEN" "$(hostname -s | awk '{print toupper($0)}')" "$NC"
fi
printf "\n"

printf "Welcome to $(hostname -f) ($(uname -r))\n"
printf "\n"
