#!/usr/bin/env bash

set -u

load="$(awk '{print $1}' /proc/loadavg 2>/dev/null)"
root_usage="$(df -h / | awk 'NR == 2 {print $5}')"
memory_usage="$(free | awk '/Mem:/ {printf "%3.1f%%", ($3 / $2) * 100}')"
swap_usage="$(free | awk '/Swap:/ {if ($2 > 0) printf "%3.1f%%", ($3 / $2) * 100; else printf "0.0%%"}')"
users_count="$(users | wc -w)"
uptime_text="$(uptime -p 2>/dev/null | sed 's/^up //')"
processes="$(ps -e --no-headers | wc -l)"
primary_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
ispconfig_config="/usr/local/ispconfig/server/lib/config.inc.php"

printf "System information as of: %s\n\n" "$(date)"
printf "System load:\t%s\tIP address:\t%s\n" "${load:-n/a}" "${primary_ip:-n/a}"
printf "Memory usage:\t%s\tSystem uptime:\t%s\n" "${memory_usage:-n/a}" "${uptime_text:-n/a}"
printf "Usage on /:\t%s\tSwap usage:\t%s\n" "${root_usage:-n/a}" "${swap_usage:-n/a}"
printf "Local users:\t%s\tProcesses:\t%s\n\n" "$users_count" "$processes"

if [ -d /usr/local/ispconfig ] && [ -r "$ispconfig_config" ]; then
    ispconfig_version="$(sed -nE "s/^[[:space:]]*define\([[:space:]]*'ISPC_APP_VERSION'[[:space:]]*,[[:space:]]*'([^']+)'.*/\1/p" "$ispconfig_config" | head -n 1)"
    printf "ISPConfig version:\t%s\n\n" "${ispconfig_version:-unknown}"
fi
